[tool.black]
line-length = 99
target-version = ['py312']
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
(
    /(
        \.git
        | \.mypy_cache
        | \.ruff_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
        | node_modules
        | __pycache__
    )/
)
'''
